name: build-push
on: [push]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-build
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: setup-build
        run: |
          docker build . --tag soccer-goals-bot
